# Table of Contents
 <p>

In [1]:
%matplotlib inline
%load_ext version_information

# Standard Library

# Third Party Libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Local Libraries

# Local Definitions
plt.rcParams["font.size"] = 18

%version_information matplotlib,numpy,pandas

Software versions
Python 3.6.3 64bit [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
IPython 6.2.1
OS Darwin 16.7.0 x86_64 i386 64bit
matplotlib 2.1.0
numpy 1.13.3
pandas 0.21.0
Tue Dec 05 09:20:26 2017 MST

In [3]:
import requests
url = 'https://umbra.nascom.nasa.gov/SEP/'
header = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36", 
    "X-Requested-With": "XMLHttpRequest"
}
r = requests.get(url,headers=header)

sep_data = pd.read_html(r.text)
sep_data

[                  0                1  \
 0    PARTICLE EVENT              NaN
 1     Start(Day/UT)  Maximum(Day/UT)
 2               NaN              NaN
 3       Apr 30/2120      May 01/1700
 4               NaN              NaN
 5       Sep 19/1430      Sep 19/2130
 6       Nov 22/1400      Nov 22/1800
 7               NaN              NaN
 8       Feb 13/0930      Feb 14/1000
 9       Apr 11/1530      Apr 11/1630
 10      Apr 29/0445      Apr 30/2000
 11      May 07/0420      May 07/0420
 12      Jun 02/0730      Jun 02/0935
 13      Jun 24/0900      Jun 25/0230
 14      Jul 13/0300      Jul 13/1000
 15      Sep 23/1035      Sep 24/0400
 16      Nov 10/2130      Nov 10/2140
 17              NaN              NaN
 18      Feb 17/2020      Feb 17/2205
 19      Apr 03/1600      Apr 03/2310
 20      Jun 06/1850      Jun 07/0005
 21      Jul 07/0015      Jul 07/1010
 22      Aug 19/0850      Aug 21/0740
 23      Sep 15/1500      Sep 16/1200
 24      Nov 16/0430      Nov 16/1300
 25              NaN              NaN
 26      Feb 06/1340      Feb 06/1850
 27      Jul 17/2300      Jul 19/1930
 28              NaN              NaN
 29      Mar 30/0900      Mar 30/2115
 ..              ...              ...
 284     Jul 17/1715      Jul 18/0600
 285     Jul 23/1545      Jul 23/2145
 286     Sep 01/1335      Sep 02/0850
 287     Sep 28/0300      Sep 28/0445
 288             NaN              NaN
 289     Mar 16/1940      Mar 17/0700
 290     Apr 11/1055      Apr 11/1645
 291     May 15/1325      May 17/1720
 292     May 22/1420      May 23/0650
 293     Jun 23 2014      Jun 24/0520
 294     Sep 30 0505      Sep 30/2005
 295     Dec 28 2150      Dec 28 2315
 296             NaN              NaN
 297     Jan 06/0915      Jan 06/1600
 298     Jan 06/0915      Jan 09/0340
 299     Feb 20/0850      Feb 20/0925
 300     Feb 25/1355      Feb 28/0845
 301     Apr 18/1525      Apr 19/0105
 302     Sep 11/0240      Sep 12/1555
 303             NaN              NaN
 304     Jun 18/1135      Jun 18/1445
 305     Jun 21/2135      Jun 22/1900
 306     Jun 26/0350      Jun 27/0030
 307     Oct 29/0550      Oct 29/1000
 308             NaN              NaN
 309     Jan 02/0430      Jan 02/0450
 310             NaN              NaN
 311     Jul 14/0900      Jul 14/2320
 312     Sep 05/0040      Sep 08/0035
 313     Sep 10/1645      Sep 11/1145

                                             2     3  \
 0    ASSOCIATED CME, FLARE, AND ACTIVE REGION   NaN
 1                  Proton Flux(pfu @ >10 MeV)  Year
 2                                         NaN  1976
 3                                          12   NaN
 4                                         NaN  1977
 5                                         200   NaN
 6                                         160   NaN
 7                                         NaN  1978
 8                                         850   NaN
 9                                          65   NaN
 10                                       1000   NaN
 11                                        100   NaN
 12                                         19   NaN
 13                                         25   NaN
 14                                         20   NaN
 15                                       2200   NaN
 16                                         38   NaN
 17                                        NaN  1979
 18                                         31   NaN
 19                                         45   NaN
 20                                        950   NaN
 21                                         50   NaN
 22                                        500   NaN
 23                                         60   NaN
 24                                         75   NaN
 25                                        NaN  1980
 26                                         12   NaN
 27                                        100   NaN
 28                                        NaN  1981
 29                                         30   NaN
 ..                                        ...   ...
 284                                       136   NaN
 285                                        12   NaN
 286                                        59   NaN
 287                                        28   NaN
 288                                       NaN  2013
 289                                        16   NaN
 290                                       114   NaN
 291                                        41   NaN
 292                                      1660   NaN
 293                                        14   NaN
 294                                       182   NaN
 295                                        29   NaN
 296                                       NaN  2014
 297                                        42   NaN
 298                                      1033   NaN
 299                                        22   NaN
 300                                       103   NaN
 301                                        58   NaN
 302                                       126   NaN
 303                                       NaN  2015
 304                                        16   NaN
 305                                      1070   NaN
 306                                        22   NaN
 307                                        23   NaN
 308                                       NaN  2016
 309                                        21   NaN
 310                                       NaN  2017
 311                                        22   NaN
 312                                       844   NaN
 313                                      1490   NaN

                                     4                5                      6  \
 0                                 NaN              NaN                    NaN
 1                                 CME  Maximum(Day/UT)  Importance(X ray/Opt)
 2                                 NaN              NaN                    NaN
 3                                 NaN      Apr 30/2114                  X2/2B
 4                                 NaN              NaN                    NaN
 5                                 NaN      Sep 19/1054                  X2/3B
 6                                 NaN      Nov 22/1006                  X1/2N
 7                                 NaN              NaN                    NaN
 8                                 NaN      Feb 13/0255                  M7/0B
 9                                 NaN      Apr 11/1353                  X2/2B
 10                                NaN      Apr 28/1306                  X5/4B
 11                                NaN      May 07/0330                  X2/2B
 12                                NaN      May 31/1009                  M5/2B
 13                                NaN      Jun 22/1709                  M2/3B
 14                                NaN              NaN                    NaN
 15                                NaN      Sep 23/1023                  X1/3B
 16                                NaN      Nov 10/0042                  M1/2N
 17                                NaN              NaN                    NaN
 18                                NaN      Feb 16/0200                  X2/2B
 19                                NaN              NaN                    NaN
 20                                NaN      Jun 05/0529                  X2/1N
 21                                NaN              NaN                    NaN
 22                                NaN      Aug 18/1416                  X6/1B
 23                                NaN      Sep 14/0802                    X2/
 24                                NaN      Nov 15/1639                  M1/0B
 25                                NaN              NaN                    NaN
 26                                NaN              NaN                    NaN
 27                                NaN      Jul 17/0603                  M3/1B
 28                                NaN              NaN                    NaN
 29                                NaN      Mar 30/0049                  M3/2N
 ..                                ...              ...                    ...
 284              Partial Halo/17 1348      Jul 17/1715                     M1
 285     Partial Halo (asymm.)/23 0236        (Farside)                    NaN
 286                 Full Halo/31 2012          31/2043                     C8
 287                 Full Halo/28 0018          27/2357                     C3
 288                               NaN              NaN                    NaN
 289          Asymm. Full Halo/15 0712          15/0658                     M1
 290          Asymm. Full Halo/11 0724          11/0716                     M6
 291          Asymm. Full Halo/15 0148          15/0148                     X1
 292               Asymm. Halo/22 1325          22/1332       M5/long duration
 293          CME (C2, COR2-A)/21 0312          21/0314                     M2
 294                  CME (C2)/29 2212          29/2337                     C1
 295                  CME (C2)/28 1736          28/1802                     C9
 296                               NaN              NaN                    NaN
 297       Asymm. Partial Halo/06 0800        (Farside)                    NaN
 298       Asymm. Partial Halo/07 1824          07/1832                     X1
 299  Asymm. Full Halo W. limb/20 0800          20/0755                     M3
 300               Asymm. Halo/25 0130          25/0049                     X4
 301                  CME (C3)/18 1325          18/1303                     M7
 302          Asymm. Full Halo/10 1800          10/1745                     X1
 303                               NaN              NaN                    NaN
 304      Narrow SW limb event/18 0125          18/0127                     M1
 305                 Full halo/21 0236          21/0236                     M2
 306      Asymmetric full halo/25 0836          25/0816                     M7
 307  Far-sided on W limb, S11/29 0236        (Farside)                    NaN
 308                               NaN              NaN                    NaN
 309             SW limb event/02 2324          02/0011                     M2
 310                               NaN              NaN                    NaN
 311      Asymmetric full halo/14 0125          14/0209                     M2
 312      Asymmetric full halo/04 2042          04/2033                     M5
 313      Asymmetric full halo/10 1600          10/1606                     X8

             7                   8
 0         NaN                 NaN
 1    Location  NOAA SECRegion No.
 2         NaN                 NaN
 3      S09W47                 700
 4         NaN                 NaN
 5      N08W58                 889
 6      N24W38                 939
 7         NaN                 NaN
 8      N22W13                1001
 9      N19W54                1057
 10     N22E41                1092
 11     N22W64                1095
 12     N23W50                1129
 13     N19E18                1164
 14        NaN                 NaN
 15     N35W50                1294
 16     N17E02                1385
 17        NaN                 NaN
 18     N15E48                1574
 19        NaN                 NaN
 20     N20E16                1781
 21        NaN                 NaN
 22     N10E90                1943
 23     N10E90                1994
 24      N34W2                2110
 25        NaN                 NaN
 26        NaN                 NaN
 27      S12E0                2562
 28        NaN                 NaN
 29      N13W7                2993
 ..        ...                 ...
 284    S17W75               11520
 285       NaN               11520
 286    S06E20                None
 287    N08W41               11577
 288       NaN                 NaN
 289    N11E12               11692
 290    N09E12               11719
 291    N11E51               11748
 292    N15W70               11745
 293    S16E66               11777
 294    N15W40   erupting filament
 295    S18E07               11936
 296       NaN                 NaN
 297       NaN               11936
 298    S15W11               11944
 299    S15W67               11976
 300    S12E82               11990
 301    S16W41               12036
 302    N16W06               12158
 303       NaN                 NaN
 304   SW limb               12365
 305    N13W00               12371
 306    N12W40               12371
 307       NaN               12434
 308       NaN                 NaN
 309    S21W73               12473
 310       NaN                 NaN
 311    S06W29               12665
 312    S11W16               12673
 313    S08W83               12673

 [314 rows x 9 columns]]